project:
  type: website
  output-dir: docs

website:
  title: "CSU 523C Projects"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Lab 1
        file: lab-01.html
      - text: Lab 2
        file: lab-02.html
      - text: Lab 3
        file: lab-03.html
      - text: Lab 4
        file: lab-04.html
      - text: Lab 5
        file: lab-05.html
      - text: Lab 6
        file: lab-06.html

format:
  html:
    theme: cosmo
    toc: true
